Fix my poor job of hand-editting configure from the autoconf 2.64 output back to 2.63.  :(

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25443,8 +25443,8 @@ fi
 
 
 # Check for --with-background-jit or --without-background-jit.
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for --with(out)-background-jit" >&5
-$as_echo_n "checking for --with(out)-background-jit... " >&6; }
+{ echo "$as_me:${as_lineno-$LINENO}: checking for --with(out)-background-jit" >&5
+echo $ECHO_N "checking for --with(out)-background-jit... " >&6; }
 
 # Check whether --with-background-jit was given.
 if test "${with_background_jit+set}" = set; then
@@ -25454,19 +25454,19 @@ fi
 
 if test "$withval" == "no"
 then
-    { $as_echo "$as_me:${as_lineno-$LINENO}: result: disabled" >&5
-$as_echo "disabled" >&6; }
+    { echo "$as_me:${as_lineno-$LINENO}: result: disabled" >&5
+echo $ECHO_N "disabled" >&6; }
 else
     if test "$BUILD_LLVM" == "disabled"
     then
-            { { $as_echo "$as_me:$LINENO: error: --with-background-jit requires --with-llvm" >&5
-$as_echo "$as_me: error: --with-background-jit requires --with-llvm" >&2;}
+            { { echo "$as_me:$LINENO: error: --with-background-jit requires --with-llvm" >&5
+echo "$as_me: error: --with-background-jit requires --with-llvm" >&2;}
    { (exit 1); exit 1; }; }
     fi
-    { $as_echo "$as_me:${as_lineno-$LINENO}: result: enabled" >&5
-$as_echo "enabled" >&6; }
+    { echo "$as_me:${as_lineno-$LINENO}: result: enabled" >&5
+echo "enabled" >&6; }
 
-$as_echo "#define WITH_BACKGROUND_COMPILATION 1" >>confdefs.h
+echo "#define WITH_BACKGROUND_COMPILATION 1" >>confdefs.h
 
 fi
 
